server.port=8080

spring.application.name=gateway
# ==========================================================
# CORS
# ==========================================================
# ==========================================================
# CORS
# ==========================================================
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:3000
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allow-credentials=true
spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

# Quan trọng cho preflight OPTIONS
# ==========================================================
# JWT
# ==========================================================

# Nên lấy từ environment variable khi chạy production
jwt.secret=6ffdcd861ce21a38a2ac4fc757fb522ecd3cb7f108043e2377e43f87cf1a51b0
jwt.expiration=86400000

# ==========================================================
# AUTH SERVICE
# ==========================================================

spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# ==========================================================
# USER SERVICE
# ==========================================================

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**

# ==========================================================
# ORDER SERVICE
# ==========================================================

spring.cloud.gateway.server.webflux.routes[2].id=order-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8083
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/orders/**

# ==========================================================
# PRODUCT SERVICE
# ==========================================================

spring.cloud.gateway.server.webflux.routes[3].id=product-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:8084
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/products/**

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.route=DEBUG
logging.level.org.springframework.cloud.gateway.handler=DEBUG
logging.level.reactor.netty.http.client=DEBUG
logging.level.reactor.netty.http.server=DEBUG