spring.datasource.url=jdbc:postgresql://localhost:5432/dev
spring.datasource.username=dev
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=your-256-bit-secret-key-change-this-in-production-please
jwt.expiration=86400000
# Tự động cập nhật cấu trúc bảng từ code Java vào database
spring.jpa.hibernate.ddl-auto=update