spring.datasource.url=jdbc:postgresql://localhost:5432/dev
spring.datasource.username=dev
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=6ffdcd861ce21a38a2ac4fc757fb522ecd3cb7f108043e2377e43f87cf1a51b0
jwt.expiration=86400000
# Tự động cập nhật cấu trúc bảng từ code Java vào database
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# Chỉ định vị trí file sql (mặc định là data.sql trong resources)
spring.sql.init.data-locations=classpath:data.sql